In [2]:
from src.data import load_data
from src.preprocessing import preprocess_dataframe
from src.features import split_data, create_classical_features

df = load_data()
df_lemma,df_stemm = preprocess_dataframe(df)
X_train_lemma, X_test_lemma, y_train_lemma, y_test_lemma = \
    split_data(df_lemma, 'text_lemma')

X_train_stem, X_test_stem, y_train_stem, y_test_stem = \
    split_data(df_stemm, 'text_stem')

print("\nOriginal:")
print(df['text'].iloc[0])

print("\nClean:")
print(df['text_clean'].iloc[0])

print("\nLemma:")
print(df['text_lemma'].iloc[0])

print("\nStem:")
print(df['text_stem'].iloc[0])

['product_id', 'product_title', 'title_en', 'user_id', 'likes', 'dislikes', 'verification_status', 'recommend', 'title', 'comment', 'advantages', 'disadvantages']
(100000, 12)
['recommend', 'title', 'comment', 'advantages', 'disadvantages']
['\\N' 'recommended' 'not_recommended' 'no_idea']
1    واقعاً عالیه سلام، قبل اینکه نظرم رو بگم میخوا...
2    خیلی سخت حوله اش در میاد گیره های فلزی خیلی سخ...
3    گوشی مقرون به صرفه همه چیز در رابطه با ظاهر ای...
4    ابعاد، استحکام و نگهداری شارژ مناسب اگر ظرفیتش...
5    اقرار بیش از حد در ایراد گرفتن سلام دوستان،،_x...
Name: text, dtype: object
label
0    16110
1    10536
2    36972
Name: count, dtype: int64

Saved clean + lemma
Saved clean + stem
text_lemma: Train size: 50894, Test size: 12724
text_stem: Train size: 50894, Test size: 12724

Original:
واقعاً عالیه سلام، قبل اینکه نظرم رو بگم میخواستم به یک موضوع مهم اشاره کنم که نظراتی که ما برای کالاها ثبت میکنیم خیلی مهم هستن، چون بسیاری از مردم عزیز با استناد به این نظرات یک کالا رو خریداری میکنن. پس بهتره ک نظر غیر کارشناسی و الکی ندیم._x000D_ _x000D_ من ۲سال این پاور بانک رو دارم، برای ۲نفر اشنا هم خریدم، پیشنهاد ویژه بود خریدم، واقعا از هر نظر عالیه، بعد گذشت ۲سال هنوزم ۵بار ایفون se رو شارژ میکنه، در خصوص زمان شارژ گفته بودن دوستان، اگر با کابل خود پاور شارژ کنید حدود ۶ساعت فول میشه، اما اگر هر کابل دیگه ای وصل کنید ۱۲تا۱۸ ساعت طول میکشه._x000D_ همزمان با این پاور یک adata 10000 هم برای همسرم خریدم ، اونم خوب درومد ولی حدود ۳۰‎٪ افت داشته و کمتر بازدهی شارژ داره._x000D_ _x000D_ طبق تجربه من و اطرافیانم ک شیائومی داشتن، اگر کالایی ک میخرید اصل باشه(فیک زیاد داره) واقعا شیائومی حرف اول و میزنه، _x000D_ anker هم برند خیلی خوب ولی گرونه، هفته پیش از دیجی خریدم a1214 اونم واقعا سبک و عالیه و بازدهی بالایی داره.(۲خروجی هوشمند داره،مجموع ۳امپر میده،حداکثر یک خروجی ۲.۴ میده)_x000D_ _x000D_ ببخشید طولانی شد. ["عمر طولانی\r","افت بسیار کم میزان شارژ\r","امپر خروجی هوشمند متناسب با امپر گوشی"] ["ندارد"]

Clean:
واقعا عالیه سلام نظرم بگم می‌خواستم موضوع مهم اشاره نظراتی کالاها ثبت خیلی مهم هستن مردم عزیز استناد نظرات کالا خریداری میکنن بهتره ک کارشناسی الکی ندیم ۲ سال پاور بانک دارم ۲ نفر اشنا خریدم پیشنهاد خریدم واقعا عالیه گذشت ۲ سال هنوزم ۵ ایفون se شارژ میکنه زمان شارژ دوستان کابل پاور شارژ ۶ ساعت فول میشه کابل دیگه‌ای وصل ۱۲ ۱۸ ساعت میکشه همزمان پاور adata ۱۰۰۰۰ همسرم خریدم اونم خوب درومد ۳۰ درصد افت کمتر بازدهی شارژ داره تجربه اطرافیانم ک شیائومی کالایی ک می‌خرید اصل باشه فیک زیاد داره واقعا شیائومی حرف میزنه anker برند خیلی خوب گرونه هفته دیجی خریدم a ۱۲۱۴ اونم واقعا سبک عالیه بازدهی بالایی داره ۲ خروجی هوشمند داره مجموع ۳ امپر میده حداکثر خروجی ۲ ٫ ۴ میده ببخشید طولانی عمر طولانی r افت بسیار کم میزان شارژ r امپر خروجی هوشمند متناسب امپر گوشی ندارد

Lemma:
واقعا عالیه سلام نظرم بگم خواست موضوع مهم اشاره نظرات کالا ثبت خیلی مهم هستن مردم عزیز استناد نظرات کالا خریداری میکنن بهتره ک کارشناسی الکی ندیم ۲ سال پاور بانک داشت ۲ نفر اشنا خرید پیشنهاد خرید واقعا عالیه گذشت ۲ سال هنوز ۵ ایفون se شارژ میکنه زمان شارژ دوستان کابل پاور شارژ ۶ ساعت فول میشه کابل دیگه وصل ۱۲ ۱۸ ساعت میکشه همزمان پاور adata ۱۰۰۰۰ همسر خرید اون خوب درومد ۳۰ درصد افت کمتر بازدهی شارژ داره تجربه اطرافیان ک شیائومی کالا ک خرید اصل باشه فیک زیاد داره واقعا شیائومی حرف میزنه anker برد خیلی خوب گرونه هفته دیج خرید a ۱۲۱۴ اون واقعا سبک عالیه بازدهی بالایی داره ۲ خروجی هوشمند داره مجموع ۳ امپر میده حداکثر خروجی ۲ ٫ ۴ میده بخشید طولانی عمر طولانی r افت بسیار کم میزان شارژ r امپر خروجی هوشمند متناسب امپر گوشید داشت

Stem:
واقعا عالیه سلا نظر بگ می‌خواس موضوع مه اشاره نظرات کالا ثب خیل مه هستن مرد عزیز استناد نظر کالا خریدار میکنن بهتره ک کارشناس الک ند ۲ سال پاور بانک دار ۲ نفر اشنا خرید پیشنهاد خرید واقعا عالیه گذ ۲ سال هنوز ۵ ایفون se شارژ میکنه ز شارژ دوس کابل پاور شارژ ۶ ساع فول میشه کابل دیگه وصل ۱۲ ۱۸ ساع میکشه همز پاور adata ۱۰۰۰۰ همسر خرید اون خوب درومد ۳۰ درصد اف ک بازده شارژ داره تجربه اطرافیان ک شیائوم کالا ک می‌خرید اصل باشه فیک زیاد داره واقعا شیائوم حرف میزنه anker برند خیل خوب گرونه هفته دیج خرید a ۱۲۱۴ اون واقعا سبک عالیه بازده بالا داره ۲ خروج هوشمند داره مجموع ۳ امپر میده حداکثر خروج ۲ ٫ ۴ میده ببخشید طولان عمر طولان r اف بسیار ک میز شارژ r امپر خروج هوشمند متناسب امپر گوش ندارد

In [3]:
from src.models.classical_models import run_classical_models
from src.evaluation import evaluate_model

# LEMMATIZATION

lemma_features = create_classical_features(X_train_lemma,X_test_lemma)
lemma_results = run_classical_models(
    lemma_features,
    y_train_lemma,
    y_test_lemma,
    evaluate_model
)

lemma_results['Preprocessing'] = 'Lemmatization'

display(
    lemma_results[
        [
            'Model',
            'Feature',
            'Accuracy',
            'Macro F1'
        ]
    ]
)

BOW Unigram: train (50894, 20000), test (12724, 20000)
BOW Bigram: train (50894, 20000), test (12724, 20000)
BOW Unigram+Bigram: train (50894, 20000), test (12724, 20000)
TFIDF Unigram: train (50894, 20000), test (12724, 20000)
TFIDF Bigram: train (50894, 20000), test (12724, 20000)
TFIDF Unigram+Bigram: train (50894, 20000), test (12724, 20000)

                  Model               Feature  Accuracy  Macro F1
0           Naive Bayes    BOW Unigram+Bigram  0.779550  0.705268
1   Logistic Regression  TFIDF Unigram+Bigram  0.766111  0.704356
2            Linear SVM  TFIDF Unigram+Bigram  0.775778  0.688067
3   Logistic Regression         TFIDF Unigram  0.744263  0.683574
4           Naive Bayes           BOW Unigram  0.764932  0.677464
5   Logistic Regression    BOW Unigram+Bigram  0.750865  0.675921
6   Logistic Regression          TFIDF Bigram  0.735696  0.673083
7           Naive Bayes            BOW Bigram  0.769962  0.671948
8           Naive Bayes  TFIDF Unigram+Bigram  0.792518  0.669147
9            Linear SVM         TFIDF Unigram  0.760846  0.665174
10  Logistic Regression           BOW Unigram  0.734282  0.662059
11           Linear SVM          TFIDF Bigram  0.742927  0.649920
12           Linear SVM    BOW Unigram+Bigram  0.735775  0.648956
13           Linear SVM           BOW Unigram  0.743084  0.647442
14  Logistic Regression            BOW Bigram  0.715734  0.647148
15          Naive Bayes          TFIDF Bigram  0.776957  0.643706
16           Linear SVM            BOW Bigram  0.715891  0.624596
17          Naive Bayes         TFIDF Unigram  0.746542  0.574804

In [4]:
# STEMMING

stem_features = create_classical_features(
    X_train_stem,
    X_test_stem
)

stem_results = run_classical_models(
    stem_features,
    y_train_stem,
    y_test_stem,
    evaluate_model
)

stem_results['Preprocessing'] = 'Stemming'

display(
    stem_results[
        [
            'Model',
            'Feature',
            'Accuracy',
            'Macro F1'
        ]
    ]
)

BOW Unigram: train (50894, 20000), test (12724, 20000)
BOW Bigram: train (50894, 20000), test (12724, 20000)
BOW Unigram+Bigram: train (50894, 20000), test (12724, 20000)
TFIDF Unigram: train (50894, 20000), test (12724, 20000)
TFIDF Bigram: train (50894, 20000), test (12724, 20000)
TFIDF Unigram+Bigram: train (50894, 20000), test (12724, 20000)

                  Model               Feature  Accuracy  Macro F1
0   Logistic Regression  TFIDF Unigram+Bigram  0.770119  0.707297
1           Naive Bayes    BOW Unigram+Bigram  0.782930  0.707214
2            Linear SVM  TFIDF Unigram+Bigram  0.779943  0.691503
3           Naive Bayes           BOW Unigram  0.765876  0.679961
4   Logistic Regression         TFIDF Unigram  0.741905  0.679874
5           Naive Bayes            BOW Bigram  0.774599  0.676779
6   Logistic Regression    BOW Unigram+Bigram  0.748664  0.673435
7   Logistic Regression          TFIDF Bigram  0.737818  0.672495
8           Naive Bayes  TFIDF Unigram+Bigram  0.794561  0.671674
9            Linear SVM         TFIDF Unigram  0.764461  0.668763
10  Logistic Regression           BOW Unigram  0.739312  0.667981
11           Linear SVM          TFIDF Bigram  0.749057  0.654144
12           Linear SVM           BOW Unigram  0.745442  0.650829
13           Linear SVM    BOW Unigram+Bigram  0.739154  0.650614
14  Logistic Regression            BOW Bigram  0.719899  0.647485
15          Naive Bayes          TFIDF Bigram  0.780494  0.646145
16           Linear SVM            BOW Bigram  0.718956  0.626894
17          Naive Bayes         TFIDF Unigram  0.750079  0.578267

In [5]:
import pandas as pd
top_results = (
    pd.concat([
        lemma_results,
        stem_results
    ])
    .sort_values(
        'Macro F1',
        ascending=False
    )
)

display(
    top_results[
        [
            'Preprocessing',
            'Model',
            'Feature',
            'Accuracy',
            'Macro F1'
        ]
    ].head(10)
)

,Preprocessing,Model,Feature,Accuracy,Macro F1
0,Stemming,Logistic Regression,TFIDF Unigram+Bigram,0.770119,0.707297
1,Stemming,Naive Bayes,BOW Unigram+Bigram,0.782930,0.707214
0,Lemmatization,Naive Bayes,BOW Unigram+Bigram,0.779550,0.705268
1,Lemmatization,Logistic Regression,TFIDF Unigram+Bigram,0.766111,0.704356
2,Stemming,Linear SVM,TFIDF Unigram+Bigram,0.779943,0.691503
2,Lemmatization,Linear SVM,TFIDF Unigram+Bigram,0.775778,0.688067
3,Lemmatization,Logistic Regression,TFIDF Unigram,0.744263,0.683574
3,Stemming,Naive Bayes,BOW Unigram,0.765876,0.679961
4,Stemming,Logistic Regression,TFIDF Unigram,0.741905,0.679874
4,Lemmatization,Naive Bayes,BOW Unigram,0.764932,0.677464